"use client";

import React, { useState, useEffect } from "react";
import {
  Image as ImageIcon,
  ZoomIn,
  X,
  Download,
  RefreshCw,
  AlertCircle,
  Loader2,
} from "lucide-react";
import { getArtifactUrl } from "../lib/api";

interface EDAGalleryProps {
  runId: string;
  edaPlotPaths?: string[] | null;
  status?: string;
}

export default function EDAGallery({ runId, edaPlotPaths, status }: EDAGalleryProps) {
  const [activeModalImg, setActiveModalImg] = useState<{ url: string; title: string } | null>(null);
  const [imgStatuses, setImgStatuses] = useState<Record<string, "loading" | "loaded" | "error">>({});
  const [retryTokens, setRetryTokens] = useState<Record<string, number>>({});

  // Defaults if empty
  const plotList =
    edaPlotPaths && edaPlotPaths.length > 0
      ? edaPlotPaths
      : ["eda_target_dist.png", "eda_correlation.png"];

  // Reset statuses when runId or plotList changes
  useEffect(() => {
    setImgStatuses({});
    setRetryTokens({});
  }, [runId, JSON.stringify(edaPlotPaths)]);

  const formatTitle = (path: string) => {
    const filename = path.split(/[\\/]/).pop() || path;
    return filename.replace(/\.[^/.]+$/, "").replace(/[_-]/g, " ").toUpperCase();
  };

  const handleRetry = (filename: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    setRetryTokens((prev) => ({ ...prev, [filename]: Date.now() }));
    setImgStatuses((prev) => ({ ...prev, [filename]: "loading" }));
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-bold text-[#1C1917]">Exploratory Data Analysis (EDA)</h3>
          <p className="text-xs text-[#574E47]">
            Automated distributions and correlation heatmaps generated by Loader & EDA agent
          </p>
        </div>
        {status === "running" && (
          <span className="flex items-center gap-1.5 text-xs font-bold text-[#CA651B] bg-[#FAC61B]/25 border border-[#FAC61B]/50 px-3 py-1 rounded-full animate-pulse">
            <Loader2 className="w-3.5 h-3.5 animate-spin text-[#CA651B]" />
            Generating plots...
          </span>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {plotList.map((path, idx) => {
          const title = formatTitle(path);
          const filename = path.split(/[\\/]/).pop() || path;
          const retryKey = retryTokens[filename];
          const baseUrl = getArtifactUrl(runId, filename);
          const url = retryKey ? `${baseUrl}?t=${retryKey}` : baseUrl;
          const imgStatus = imgStatuses[filename] || "loading";

          return (
            <div
              key={`${filename}-${idx}`}
              className="group relative bg-[#FAF6F0] border border-[#C8BCAB] rounded-2xl overflow-hidden shadow-xs hover:border-[#CA651B] transition duration-150"
            >
              <div className="p-3 border-b border-[#C8BCAB] flex items-center justify-between bg-[#E5DDD0]">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 rounded-lg bg-[#08979D]/15 text-[#08979D]">
                    <ImageIcon className="w-3.5 h-3.5" />
                  </div>
                  <span className="text-xs font-bold text-[#1C1917]">{title}</span>
                </div>
                <div className="flex items-center gap-1.5">
                  {imgStatus === "loaded" && (
                    <>
                      <button
                        onClick={() => setActiveModalImg({ url, title })}
                        className="p-1.5 rounded-lg text-[#574E47] hover:text-[#CA651B] hover:bg-[#DDD4C5] transition cursor-pointer"
                        title="Enlarge Image"
                      >
                        <ZoomIn className="w-3.5 h-3.5" />
                      </button>
                      <a
                        href={url}
                        download={filename}
                        target="_blank"
                        rel="noreferrer"
                        className="p-1.5 rounded-lg text-[#574E47] hover:text-[#CA651B] hover:bg-[#DDD4C5] transition cursor-pointer"
                        title="Download Image"
                      >
                        <Download className="w-3.5 h-3.5" />
                      </a>
                    </>
                  )}
                  <button
                    onClick={(e) => handleRetry(filename, e)}
                    className="p-1.5 rounded-lg text-[#574E47] hover:text-[#CA651B] hover:bg-[#DDD4C5] transition cursor-pointer"
                    title="Reload Plot"
                  >
                    <RefreshCw className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              <div
                className={`p-4 flex items-center justify-center bg-[#ECE4D8] min-h-[260px] relative ${
                  imgStatus === "loaded" ? "cursor-pointer" : ""
                }`}
                onClick={() => {
                  if (imgStatus === "loaded") {
                    setActiveModalImg({ url, title });
                  }
                }}
              >
                {/* Loading state */}
                {imgStatus === "loading" && (
                  <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 text-[#574E47] bg-[#ECE4D8]/80">
                    <Loader2 className="w-6 h-6 animate-spin text-[#CA651B]" />
                    <span className="text-xs font-bold text-[#CA651B]">Loading plot...</span>
                  </div>
                )}

                {/* Error state */}
                {imgStatus === "error" && (
                  <div className="flex flex-col items-center justify-center text-center p-6 space-y-2.5">
                    <div className="p-2.5 rounded-xl bg-[#B83E16]/10 text-[#B83E16] border border-[#B83E16]/30">
                      <AlertCircle className="w-5 h-5" />
                    </div>
                    <div className="space-y-0.5">
                      <p className="text-xs font-bold text-[#1C1917]">Plot not available</p>
                      <p className="text-[11px] text-[#574E47] max-w-[220px]">
                        {status === "running"
                          ? "Still being rendered by the EDA agent."
                          : "File was not generated or could not be found."}
                      </p>
                    </div>
                    <button
                      onClick={(e) => handleRetry(filename, e)}
                      className="mt-1 flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#FAF6F0] hover:bg-[#E5DDD0] text-[#CA651B] text-xs font-bold border border-[#C8BCAB] shadow-2xs transition cursor-pointer"
                    >
                      <RefreshCw className="w-3 h-3" />
                      Retry
                    </button>
                  </div>
                )}

                {/* Main image */}
                <img
                  src={url}
                  alt={title}
                  onLoad={() => {
                    setImgStatuses((prev) => ({ ...prev, [filename]: "loaded" }));
                  }}
                  onError={() => {
                    setImgStatuses((prev) => ({ ...prev, [filename]: "error" }));
                  }}
                  className={`max-h-72 object-contain rounded-lg shadow-xs group-hover:scale-[1.01] transition duration-200 ${
                    imgStatus === "loaded" ? "opacity-100" : "opacity-0 absolute"
                  }`}
                />
              </div>
            </div>
          );
        })}
      </div>

      {/* Lightbox Zoom Modal */}
      {activeModalImg && (
        <div
          className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4"
          onClick={() => setActiveModalImg(null)}
        >
          <div
            className="relative max-w-4xl w-full bg-[#FAF6F0] border border-[#C8BCAB] rounded-2xl overflow-hidden shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-4 border-b border-[#C8BCAB] flex items-center justify-between bg-[#E5DDD0]">
              <h4 className="text-sm font-bold text-[#1C1917]">{activeModalImg.title}</h4>
              <button
                onClick={() => setActiveModalImg(null)}
                className="p-1.5 rounded-lg text-[#574E47] hover:text-[#1C1917] hover:bg-[#DDD4C5] transition cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="p-6 flex items-center justify-center bg-[#ECE4D8] max-h-[80vh] overflow-auto">
              <img
                src={activeModalImg.url}
                alt={activeModalImg.title}
                className="max-h-[70vh] object-contain rounded-lg"
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
